document.write("<script src=\"\/js\/yiyan.js\"><\/script>");
document.write("<div class=\"footer\">");
document.write("	<div class=\"other-link clearfix\">");
document.write("		<div class=\"link-look clearfix\">");
document.write("			<div class=\"link-list\">");
document.write("				<h3 class=\"link-title\">我们<\/h3>");
document.write("				<ul>");
document.write("           <li>");
document.write("			 <a href=\"/about\">关于我们<\/a>");
document.write("		   <\/li>");
document.write("           <li>");
document.write("             <a href=\"/qf\">赞助我们<\/a><br>");
document.write("           <\/li>");
document.write("           <li>");
document.write("              <a href=\"http://qm.qq.com/cgi-bin/qm/qr?k=YLgBCFSls_umLedU6ogaQFNCZAMf1n4U&noverify=0&personal_qrcode_source=3\">站长QQ<\/a>");
document.write("           <\/li>");
document.write("				<\/ul>");
document.write("			<\/div>");
document.write("			<div class=\"link-list\">");
document.write("				<h3 class=\"link-title\">友情链接<\/h3>");
document.write("				<ul>");
document.write("					<li>");
document.write("						<a href=\"https://rainyun.com/NjI4OTk=\" target=\"_blank\">雨云<\/a>");
document.write("					<\/li>");
document.write("					<li>");
document.write("						<a href=\"https://daiqitao.github.io\" target=\"_blank\">daiqitao的个人主页<\/a>");
document.write("					<\/li>");
document.write("					<li>");
document.write("						<a href=\"https://40code.com\" target=\"_blank\">40code编程社区<\/a>");
document.write("					<\/li>");
document.write("				<\/ul>");
document.write("			<\/div>");
document.write("   <div><h3 class=\"logo-footer\"><a href=\"\/\"><img src=\"\/img\/图片1.png\" height=\"40\" alt=\"银河编程网\" title=\"回到首页\"><\/a><\/h3><\/div>");
document.write("			    随机文案：<span id=\"yiyan\"><\/span><br><br>");
document.write("                “发掘无限创意，开启编程之旅！”<br> ");
document.write("                加入我们：<a href=\"/jr_us\">点击申请</a><br>");
document.write("			<\/div>");
document.write("             <div class=\"footer-bottom\">");
document.write("		                <p>© 2022-2024 银河编程工作室版权所有<\/p>");
document.write("             <\/div>");
document.write("		<\/div>");
document.write("	<\/div>");
