document.write("	<div class=\"screen\">");
document.write("		<nav class=\"navbar navbar-expand-lg nav\">");
document.write("			<div class=\"container-fluid\">");
document.write("				<div class=\"collapse navbar-collapse\">");
document.write("					<ul class=\"navbar-nav\">");
document.write("						<li class=\"nav-item\"><a class=\"navbar-brand\" href=\"\/\"><img src=\"\/img\/图片1.png\" alt=\"logo\" alt=\"银河编程网\" width=\"130\" title=\"首页\"><\/a><\/li>");
document.write("                        <li class=\"nav-item\"><button class=\"btn btn-outline-secondary2\" onclick=\"location.href='/about'\">关于我们<\/button><\/li>");
document.write("                        <li class=\"nav-item\"><button class=\"btn btn-outline-secondary2\" onclick=\"location.href='/qf'\">赞助银河编程<\/button><\/li>");
document.write("				    <\/ul>");
document.write("				<\/div>");
document.write("	        <\/div>");
document.write("       <\/nav>");
document.write("	<\/div>");
document.write("	<div class=\"i\"><\/div>");